### PR TITLE
Sass linter reporter

### PR DESCRIPTION
**Pull request by jotka**
custom sass linter reporter to get rid of another ruby gem.

### CODE REVIEW

**Comment by hindsholm** [comment]
Thankyou, that was fast! But it is SCSS and not SASS ;-)

**Comment by jotka** [comment]
yeah, I will rename those references in code into "sass" :). BTW did the Jenkins pick up the reports?

**Comment by hindsholm** [comment]
I don't know yet if Jenkins will pick up the reports, but hopefully later today...

**Comment by hindsholm** [comment]
I guess I wasn't awake this morning - SASS and SCSS is the same thing of course, just with a slightly different syntax. So I guess it doesn't matter.

**Comment by jotka** [comment]
sure, no problem. cheers :sunglasses:

**Comment by AllanHoejgaardJensen** [comment]
Imho the language should be scss, not sass - scss is the newest - so it is
not the same - awake or not ;-)

2016-02-18 16:29 GMT+01:00 Morten Hindsholm <notifications@github.com>:

**Pull request merged**
